name: Translation

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  translation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Test messages
      run: python3 -m unittest tests.test_messages

    - name: Test monsters
      run: python3 -m unittest tests.test_monsters

    - name: Test NPCs
      run: python3 -m unittest tests.test_npcs

    - name: Test items
      run: python3 -m unittest tests.test_items
